config/routes.rb
CommishApp::Application.routes.draw do
  devise_for :users

  resources :players, only: [ :index, :show ]
  resources :weeks,   only: [ :index, :show ]
  resources :fantasy_teams do
    member do
      get :update_roster, path: 'update-roster'
    end
  end
  resources :fantasy_leagues do
    member do
      get :update_rosters, path: 'update-rosters'
    end
  end
  match "injuries/update-all/:week" => 'injuries#update_all', as: :update_all_injuries
  match "injuries(/:week)" => 'injuries#index', as: :injuries
  match 'update-projections(/:week)' => 'projections#update', as: :update_projections

  match 'request_access' => 'users#request_access', as: :request_access

  root :to => "home#index"
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

  def index
    @weeks = Projection.select('distinct week').order(:week).map(&:week)
  end

  def show
    @week = params[:id]
    @projections = Projection.includes(:player).where(week: @week).order(:rank)
  end
end

app/views/weeks/index.html.haml
= content_for :title do
  %h1
    Weeks

%ul
  -@weeks.each do |w|
    %li= link_to "Week #{w}", week_path(w)

app/views/weeks/show.html.haml
= content_for :title do
  %h1
    Week #{@week} Rankings

.row
  .two.columns
    %ul.side-nav
      %li= link_to 'Update Projections', update_projections_path
  .ten.columns
    %table
      %thead
        %tr
          %th Rank
          %th Player
          %th Points
      %tbody
        -@projections.each do |pro|
          %tr
            %td= pro.rank
            %td= link_to pro.player, player_path(pro.player)
            %td= pro.standard.round(2)