config/routes.rb
CommishApp::Application.routes.draw do
  devise_for :users

  resources :players, only: [ :index, :show ]
  resources :weeks,   only: [ :index, :show ]
  resources :fantasy_teams do
    member do
      get :update_roster, path: 'update-roster'
    end
  end
  resources :fantasy_leagues do
    member do
      get :update_rosters, path: 'update-rosters'
    end
  end
  match "injuries/update-all/:week" => 'injuries#update_all', as: :update_all_injuries
  match "injuries(/:week)" => 'injuries#index', as: :injuries
  match 'update-projections(/:week)' => 'projections#update', as: :update_projections

  match 'request_access' => 'users#request_access', as: :request_access

  root :to => "home#index"
end

app/models/fantasy_league.rb
class FantasyLeague < ActiveRecord::Base
  has_many :fantasy_teams
  belongs_to :user

  attr_accessible :espn_id, :name, :year

  validates_presence_of :name

  def unclaimed_players
    Player.where("ffn_id not in (?)", players.map(&:ffn_id))
  end

  def players
    fantasy_teams.map{|t| t.players }.flatten
  end

  def update_rosters(team_id=nil)
    if team_id && team = fantasy_teams.find(team_id)
      team.update_roster
    else
      fantasy_teams.each do |t|
        t.update_roster
      end
    end
  end
end

app/controllers/fantasy_leagues_controller.rb
class FantasyLeaguesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @fantasy_leagues = current_user.fantasy_leagues
  end

  def show
    @fantasy_league = FantasyLeague.find(params[:id])
    @current_week = Projection.maximum(:week)

    @unclaimed_players = @fantasy_league.unclaimed_players.with_weekly_projections(@current_week)
  end

  def new
    @fantasy_league = FantasyLeague.new
  end

  def create
    @fantasy_league = FantasyLeague.new(params[:fantasy_league])

    if @fantasy_league.save
      current_user.fantasy_leagues << @fantasy_league
      flash[:success] = "#{@fantasy_league.name} created."
      redirect_to @fantasy_league
    else
      render 'new'
    end
  end

  def edit
    @fantasy_league = FantasyLeague.find(params[:id])
  end

  def update
    @fantasy_league = FantasyLeague.find(params[:id])

    if @fantasy_league.update_attributes(params[:fantasy_league])
      flash[:success] = "#{@fantasy_league.name} updated."
      redirect_to @fantasy_league
    else
      render 'new'
    end
  end

  def delete
    @fantasy_league = FantasyLeague.find(params[:id])

    @fantasy_league.destroy

    flash[:notice] = "#{@fantasy_league.name} deleted."
    redirect_to fantasy_leagues_path
  end

  def update_rosters
    @fantasy_league = FantasyLeague.find(params[:id])

    errors = []
    @fantasy_league.fantasy_teams.each do |team|
      errors + team.update_roster.map{|e| "#{team.name}: #{e}"}
    end

    if errors.any?
      flash[:alert] = errors.join("<br>").html_safe
    else
      flash[:success] = 'Rosters updated successfully.'
    end

    redirect_to @fantasy_league
  end
end

app/views/fantasy_leagues/_form.haml
=form_for @fantasy_league do |f|
  =show_errors_for(@fantasy_league)

  .row
    .one.columns
      =f.label :name
    .three.columns.end
      =f.text_field :name
  .row
    .one.columns
      =f.label :espn_id
    .three.columns.end
      =f.text_field :espn_id
  .row
    .one.columns
      =f.label :year
    .three.columns.end
      =f.text_field :year

  .row
    .twelve.columns
      -submit_text = @fantasy_league.new_record? ? 'Add' : 'Save'
      =f.submit submit_text
      -unless @fantasy_league.new_record?
        =link_to 'cancel', @fantasy_league
        %br
        %br
        =link_to 'delete', @fantasy_league, method: 'delete'

app/views/fantasy_leagues/_sidebar.haml
%ul.side-nav
  %li{ class: active_nav_action('index') }
    =link_to 'All Leagues', fantasy_leagues_path
  %li.divider
  %li{ class: active_nav_action('new') }
    =link_to 'New League', new_fantasy_league_path

app/views/fantasy_leagues/edit.html.haml
= content_for :title do
  %h1= @fantasy_league.name

=render 'form'

app/views/fantasy_leagues/index.html.haml
= content_for :title do
  %h1 Fantasy Leagues

.row
  .two.columns
    = render 'sidebar'
  .ten.columns
    -if @fantasy_leagues.any?
      %ul
        -@fantasy_leagues.each do |league|
          %li= link_to league.name, league
    -else
      You don't have any leagues. 
      = link_to 'Create a new league.', new_fantasy_league_path

app/views/fantasy_leagues/new.html.haml
= content_for :title do
  %h1 New Fantasy League

= render 'form'

app/views/fantasy_leagues/show.html.haml
= content_for :title do
  %h1= @fantasy_league.name

.row
  .two.columns
    %dl
      %dt ESPN ID:
      %dd= @fantasy_league.espn_id
      %dt Year:
      %dd= @fantasy_league.year

    %ul.side-nav
      %li.pre-icon.update-all
        = link_to 'Update all team rosters', update_rosters_fantasy_league_path
      %li.divider
      %li= link_to 'Add Team', new_fantasy_team_path
      %li= link_to 'Edit', edit_fantasy_league_path(@fantasy_league)
  .five.columns
    %h4 Week #{@current_week}
    -if @fantasy_league.fantasy_teams.any?
      %table
        %thead
          %tr
            %th Team
            %th Projections
        %tbody
          -@fantasy_league.fantasy_teams.each do |team|
            %tr
              %td= link_to team, team
              %td= team.weekly_projection(@current_week)

    -else
      #{@fantasy_league.name} doesn't have any teams.
      = link_to 'Create one here.', new_fantasy_team_path
  .five.columns
    %h4 Top Unclaimed Players
    %table
      %thead
        %tr
          %th Name
          %th Position
          %th Team
          %th Rank
          %th Points
      %tbody
        -@unclaimed_players.each do |p|
          %tr
            %td= render p
            %td= p.position
            %td= p.team
            %td.align-right= p.weekly_projection(@current_week, :rank).to_i
            %td.align-right= p.weekly_projection(@current_week)