config/routes.rb
CommishApp::Application.routes.draw do
  devise_for :users

  resources :players, only: [ :index, :show ]
  resources :weeks,   only: [ :index, :show ]
  resources :fantasy_teams do
    member do
      get :update_roster, path: 'update-roster'
    end
  end
  resources :fantasy_leagues do
    member do
      get :update_rosters, path: 'update-rosters'
    end
  end
  match "injuries/update-all/:week" => 'injuries#update_all', as: :update_all_injuries
  match "injuries(/:week)" => 'injuries#index', as: :injuries
  match 'update-projections(/:week)' => 'projections#update', as: :update_projections

  match 'request_access' => 'users#request_access', as: :request_access

  root :to => "home#index"
end

app/models/fantasy_team.rb
class FantasyTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :fantasy_league
  has_many :fantasy_players
  has_many :players, through: :fantasy_players, uniq: true

  attr_accessible :fantasy_league_id, :name, :espn_id

  def to_s
    name
  end

  def weekly_projection(week, type=:standard)
    points = 0
    fantasy_players.each{|p| points += p.weekly_projection(week, type) if p.starter }
    points
  end

  def update_roster
    link = "http://games.espn.go.com/ffl/clubhouse?leagueId=#{fantasy_league.espn_id}&teamId=#{espn_id}&seasonId=#{fantasy_league.year}"

    page = Nokogiri::HTML(open(link))
    player_table = page.search("//table[@id='playertable_0']")
    player_data = player_table.search("//td[@class='playertablePlayerName']")

    errors = []
    count = 1
    if player_data.any?
      fantasy_players.destroy_all

      player_data.each do |d|
        text = d.text.split(', ')

        if text.length == 1 # name is a defense team
          team_name = text[0].split(' ')[0]
          if player = Player.where("name like '%#{team_name}%'").first
            fantasy_players << FantasyPlayer.new(player: player, starter: count <= 9)
          else
            errors << "\nCouldn't find defense team with name '#{name}'"
          end
        else #name is a player
          name = text[0].gsub('*', '')
          modifiers = text[1].gsub("\u00A0", ' ').split(' ')
          #team = modifiers[0].upcase
          position = modifiers[1].upcase

          if player = Player.where(name: name, position: position).first
            fantasy_players << FantasyPlayer.new(player: player, starter: count <= 9)
          else
            errors << "\nCouldn't find player with name '#{name}'"
          end
        end
        count += 1
      end
    else
      errors << "No player links found on ESPN. Maybe ESPN changed their page markup?"
    end
    errors
  end
end

app/controllers/fantasy_teams_controller.rb
class FantasyTeamsController < ApplicationController

  def index
    @fantasy_teams = FantasyTeam.where(user_id: current_user.id)
  end

  def show
    @fantasy_team = FantasyTeam.find(params[:id])
    @fantasy_players = @fantasy_team.fantasy_players
    @players = @fantasy_players.map(&:player)
    @current_week = Projection.maximum(:week)
    @total_points = @fantasy_team.weekly_projection(@current_week)
    @projections = Projection.for_week(@current_week)
    @fantasy_league = @fantasy_team.fantasy_league
    @league_players = @fantasy_league.players
  end

  def new
    @fantasy_team = FantasyTeam.new
  end

  def create
    @fantasy_team = FantasyTeam.new(params[:fantasy_team])
    current_user.fantasy_teams << @fantasy_team

    if @fantasy_team.save
      flash[:success] = "Created #{@fantasy_team.name}"
      redirect_to @fantasy_team
    else
      render 'new'
    end
  end

  def edit
    @fantasy_team = FantasyTeam.find(params[:id])
  end

  def update
    @fantasy_team = FantasyTeam.find(params[:id])

    if @fantasy_team.update_attributes(params[:fantasy_team])
      flash[:success] = "Updated #{@fantasy_team.name}"
      redirect_to @fantasy_team
    else
      render 'edit'
    end
  end

  def destroy
  end

  def update_roster
    @fantasy_team = FantasyTeam.find(params[:id])

    errors = @fantasy_team.update_roster

    if errors.any?
      flash[:alert] = errors.join("<br>").html_safe
    else
      flash[:success] = 'Roster updated successfully.'
    end

    redirect_to @fantasy_team
  end
end

app/views/fantasy_teams/_form.haml
=form_for @fantasy_team do |f|
  =show_errors_for(@fantasy_team)

  .row
    .one.columns
      =f.label :name
    .three.columns.end
      =f.text_field :name
  .row
    .one.columns
      =f.label :fantasy_league_id
    .three.columns.end
      =f.collection_select :fantasy_league_id, FantasyLeague.all, :id, :name
  .row
    .one.columns
      =f.label :espn_id
    .three.columns.end
      =f.number_field :espn_id

  .row
    .twelve.columns
      -submit_text = @fantasy_team.new_record? ? 'Add' : 'Save'
      =f.submit submit_text
      -unless @fantasy_team.new_record?
        =link_to 'cancel', @fantasy_team
        %br
        %br
        =link_to 'delete', @fantasy_team, method: 'destroy'

app/views/fantasy_teams/edit.html.haml
= content_for :title do
  %h1= @fantasy_team.name

=render 'form'

app/views/fantasy_teams/index.html.haml
= content_for :title do
  %h1 Fantasy Teams

-if @fantasy_teams.any?
  %ul
    -@fantasy_teams.each do |team|
      %li= link_to team, fantasy_team_path(team)
-else
  .well
    You don't have any teams.
    = link_to "Create a new Fantasy team here", new_fantasy_team_path

app/views/fantasy_teams/new.html.haml
= content_for :title do
  %h1 New Fantasy Team

= render 'form'

app/views/fantasy_teams/show.html.haml
= content_for :title do
  %h1= @fantasy_team.name

.row
  .two.columns
    %ul.side-nav
      -if @fantasy_team.fantasy_league.espn_id
        %li= link_to "Update roster", update_roster_fantasy_team_path
      %li= link_to 'Edit', edit_fantasy_team_path(@fantasy_team)
      %li.divider
      %li= link_to @fantasy_team.fantasy_league.name, @fantasy_team.fantasy_league
  .five.columns
    -if @fantasy_players.any?
      %table
        %thead
          %tr
            %th Player
            %th Position
            %th Team
            %th Projection
        %tbody
          -@fantasy_players.each do |p|
            %tr{ class: p.starter ? "starter" : ''  }
              %td= render p.player
              %td= p.position
              %td= p.team
              %td.align-right= p.weekly_projection(@current_week)
        %tfoot
          %tr
            %td{colspan: 3 } Total Points:
            %td.align-right= @total_points
    -else
      Your team doesn't have any players.
  .five.columns
    -if @projections.any?
      %table
        %thead
          %tr
            %th{colspan: 2} Player
            %th Points
        %tbody
          -@projections.each do |pro|
            %tr
              -fantasy_player = pro.player.fantasy_players.where(fantasy_team_id: @fantasy_league.fantasy_teams.map(&:id)).first 
              -starter = fantasy_player && fantasy_player.starter
              -c = starter ? 'starter' : @league_players.include?(pro.player) ? 'no-start' : ''
              -team = fantasy_player ? fantasy_player.fantasy_team.name : ''
              %td.pre-icon{ class: c, title: team }

              -c = @players.include?(pro.player) ? 'on-team' : ''
              %td{class: c}
                = render pro.player
                #{pro.player.position}

              %td= pro.standard.round(2)
      %table
    -else
      It looks like there aren't any projections for this week.
      =link_to 'Get the lastest projections here', update_projections_path