config/routes.rb
CommishApp::Application.routes.draw do
  devise_for :users

  resources :players, only: [ :index, :show ]
  resources :weeks,   only: [ :index, :show ]
  resources :fantasy_teams do
    member do
      get :update_roster, path: 'update-roster'
    end
  end
  resources :fantasy_leagues do
    member do
      get :update_rosters, path: 'update-rosters'
    end
  end
  match "injuries/update-all/:week" => 'injuries#update_all', as: :update_all_injuries
  match "injuries(/:week)" => 'injuries#index', as: :injuries
  match 'update-projections(/:week)' => 'projections#update', as: :update_projections

  match 'request_access' => 'users#request_access', as: :request_access

  root :to => "home#index"
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  -if msg.is_a?(String)
    .flash{ id: "flash_#{name}" }= msg 

app/views/layouts/_navigation.html.haml
%ul.nav-bar.top
  %li.brand= link_to "Commish App", root_path, :class => 'brand'
  %li{ class: active_nav('players') }
    = link_to 'Players', players_path
  %li{ class: active_nav('weeks') }
    = link_to 'Weeks', weeks_path
  %li{ class: active_nav('injuries') }
    = link_to 'Injuries', injuries_path
  -if user_signed_in?
    %li{ class: active_nav('fantasy_leagues') }
      = link_to 'Leagues', fantasy_leagues_path
    %li{ class: active_nav('fantasy_teams') }
      = link_to 'Teams', fantasy_teams_path

  -if user_signed_in?
    %li.right= link_to "Log out", destroy_user_session_path
  -else
    %li.right= link_to 'Log in', new_user_session_path

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? "#{strip_tags(yield(:title))} | Commish App" : "Commish App"
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        -if content_for?(:title)
          .row
            .twelve.columns
              = yield(:title)
        .row
          .twelve.columns
            = yield
      %footer
    / ! end of #container